/* Regenerates js/organic-posts.js + js/paid-ads.js from
   assets/organic-posts/ and assets/paid-ads/.
   Run after adding/renaming files:  node scripts/gen-social.js

   Filename conventions (rename to control order — numeric-aware):
     static-<n>-<slug>.jpg              -> a single feed post
     carousel-<n>-<slug>-<i>.jpg        -> image <i> of carousel <n>
   Add a new post: drop in a new `static-<next-n>-name.jpg`, or a set of
   `carousel-<next-n>-name-1.jpg, -2.jpg, …`. Re-run this script after. */
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..", "assets");
const IMG = /\.(jpe?g|png|webp)$/i;
const byName = (a, b) => a.localeCompare(b, undefined, { numeric: true });
const pretty = (s) => s.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

function build(dir) {
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir).filter((f) => IMG.test(f));
  const statics = [];
  const carousels = {};
  for (const f of files) {
    const base = f.replace(/\.(jpe?g|png|webp)$/i, "");
    let m = base.match(/^static-(\d+)-(.+)$/);
    if (m) {
      statics.push({ n: Number(m[1]), file: f, label: pretty(m[2]) });
      continue;
    }
    m = base.match(/^carousel-(\d+)-(.+)-(\d+)$/);
    if (m) {
      const [, n, slug] = m;
      (carousels[n] = carousels[n] || { n: Number(n), label: pretty(slug), files: [] }).files.push(f);
      continue;
    }
    // Unrecognized filename — still show it so nothing silently disappears.
    statics.push({ n: 999 + statics.length, file: f, label: pretty(base) });
  }
  Object.values(carousels).forEach((c) => c.files.sort(byName));
  const posts = [
    ...statics.map((s) => ({ type: "static", n: s.n, label: s.label, file: s.file })),
    ...Object.values(carousels).map((c) => ({ type: "carousel", n: c.n, label: c.label, files: c.files })),
  ].sort((a, b) => a.n - b.n);
  return posts;
}

function write(varName, dir, outFile) {
  const posts = build(path.join(root, dir));
  fs.writeFileSync(
    path.join(__dirname, "..", "js", outFile),
    `/* AUTO-GENERATED by scripts/gen-social.js — do not edit by hand.\n   ${posts.length} post(s) from assets/${dir}/. */\nconst ${varName} = ${JSON.stringify(posts)};\n`
  );
  console.log(`js/${outFile} written: ${posts.length} posts (${posts.filter((p) => p.type === "carousel").length} carousels)`);
}

write("ORGANIC_POSTS", "organic-posts", "organic-posts.js");
write("PAID_ADS", "paid-ads", "paid-ads.js");
