/* Regenerates js/posters.js from assets/posters/.
   Run after adding/moving posters:  node scripts/gen-posters.js

   CATEGORIES = subfolders. Drag posters into assets/posters/<category>/
   (events, merchandise, announcements, greetings, mockups — or make a
   new folder; its name becomes the section label). Files still in the
   root render under a single "All Posters"/"More" section, so nothing
   breaks while sorting is in progress. Filenames never need renaming.

   ORDER: by filename, ascending (numeric-aware) — rename files 1.jpg,
   2.jpg, 10.jpg… to control exactly how they appear. */
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..", "assets", "posters");
const IMG = /\.(jpe?g|png|webp)$/i;
const pretty = (n) => n.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

const parsePosterFilename = (filename) => {
  const name = filename.replace(/\.[^.]+$/, "");
  const match = name.match(/^(\d+)(?:\s*\((\d+)\))?$/);
  return match
    ? { type: "numeric", base: Number(match[1]), dup: match[2] ? Number(match[2]) : 0 }
    : { type: "string", value: name.toLowerCase() };
};

const byName = (a, b) => {
  const pa = parsePosterFilename(a);
  const pb = parsePosterFilename(b);

  if (pa.type === "numeric" && pb.type === "numeric") {
    if (pa.base !== pb.base) return pa.base - pb.base;
    return pa.dup - pb.dup;
  }

  if (pa.type === "numeric") return -1;
  if (pb.type === "numeric") return 1;

  return a.localeCompare(b, undefined, { numeric: true });
};

const cats = [];
const loose = [];
const categoryOrder = ["greetings", "announcements", "events", "merchandise", "mockups"];
for (const entry of fs.readdirSync(root, { withFileTypes: true }).sort((a, b) => {
  if (a.isDirectory() && b.isDirectory()) {
    const ai = categoryOrder.indexOf(a.name.toLowerCase());
    const bi = categoryOrder.indexOf(b.name.toLowerCase());
    if (ai !== -1 || bi !== -1) {
      return (ai === -1 ? Number.MAX_SAFE_INTEGER : ai) - (bi === -1 ? Number.MAX_SAFE_INTEGER : bi);
    }
  }
  return a.name.localeCompare(b.name);
})) {
  if (entry.isDirectory()) {
    const files = fs.readdirSync(path.join(root, entry.name)).filter((f) => IMG.test(f)).sort(byName);
    if (files.length) cats.push({ dir: entry.name, label: pretty(entry.name), files });
  } else if (IMG.test(entry.name)) {
    loose.push(entry.name);
  }
}
loose.sort(byName);
if (loose.length) cats.push({ dir: "", label: cats.length ? "More" : "All Posters", files: loose });

const total = cats.reduce((n, c) => n + c.files.length, 0);
fs.writeFileSync(
  path.join(__dirname, "..", "js", "posters.js"),
  `/* AUTO-GENERATED by scripts/gen-posters.js — do not edit by hand.
   ${total} poster(s) in ${cats.length} section(s) from assets/posters/. */
const POSTERS = ${JSON.stringify(cats)};
`
);
console.log("js/posters.js written:", total, "posters in", cats.length, "sections:", cats.map((c) => `${c.label}(${c.files.length})`).join(", "));
